/* Generated By:JavaCC: Do not edit this line. ExpressionCCParserTreeConstants.java Version 5.0 */
package org.smile.expression.parser;

public interface ExpressionCCParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTEXPRESSION = 1;
  public int JJTOREXPRESSION = 2;
  public int JJTANDEXPRESSION = 3;
  public int JJTCONDITIONPARTEXPRESSION = 4;
  public int JJTCONDITIONEXPRESSION = 5;
  public int JJTFIELDNAME = 6;
  public int JJTONEKEYWORD = 7;
  public int JJTNUMBEREXPRESSION = 8;
  public int JJTNUMBER = 9;
  public int JJTOPERATEWORD = 10;
  public int JJTLIKEWORD = 11;
  public int JJTBITWISEANDOR = 12;
  public int JJTADDITIVEEXPRESSION = 13;
  public int JJTTRINOMIALEXPRESSION = 14;
  public int JJTBINARYEXPRESSION = 15;
  public int JJTVOLUATION = 16;
  public int JJTFUNCTION = 17;
  public int JJTMULTIPLICATIVEEXPRESSION = 18;
  public int JJTBITWISEXOR = 19;


  public String[] jjtNodeName = {
    "parse",
    "Expression",
    "OrExpression",
    "AndExpression",
    "ConditionPartExpression",
    "ConditionExpression",
    "FieldName",
    "OneKeyWord",
    "NumberExpression",
    "Number",
    "OperateWord",
    "LikeWord",
    "BitwiseAndOr",
    "AdditiveExpression",
    "TrinomialExpression",
    "BinaryExpression",
    "Voluation",
    "Function",
    "MultiplicativeExpression",
    "BitwiseXor",
  };
}
/* JavaCC - OriginalChecksum=3397cedc1081ac31335532ec9532c693 (do not edit this line) */
