/* Generated By:JavaCC: Do not edit this line. OrmWhereSqlParserTreeConstants.java Version 5.0 */
package org.smile.orm.parser;

public interface OrmWhereSqlParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTEXPRESSION = 1;
  public int JJTOREXPRESSION = 2;
  public int JJTINMULTIQUSTION = 3;
  public int JJTANDEXPRESSION = 4;
  public int JJTCONDITIONPARTEXPRESSION = 5;
  public int JJTCONDITIONEXPRESSION = 6;
  public int JJTFIELDNAME = 7;
  public int JJTONEKEYWORD = 8;
  public int JJTNUMBEREXPRESSION = 9;
  public int JJTNUMBER = 10;
  public int JJTOPERATEWORD = 11;
  public int JJTLIKEWORD = 12;
  public int JJTBITWISEANDOR = 13;
  public int JJTADDITIVEEXPRESSION = 14;
  public int JJTBINARYEXPRESSION = 15;
  public int JJTFUNCTION = 16;
  public int JJTMULTIPLICATIVEEXPRESSION = 17;
  public int JJTBITWISEXOR = 18;


  public String[] jjtNodeName = {
    "parse",
    "Expression",
    "OrExpression",
    "InMultiQustion",
    "AndExpression",
    "ConditionPartExpression",
    "ConditionExpression",
    "FieldName",
    "OneKeyWord",
    "NumberExpression",
    "Number",
    "OperateWord",
    "LikeWord",
    "BitwiseAndOr",
    "AdditiveExpression",
    "BinaryExpression",
    "Function",
    "MultiplicativeExpression",
    "BitwiseXor",
  };
}
/* JavaCC - OriginalChecksum=ad07516b3f5a9c10314b371059e600dc (do not edit this line) */
