/* Generated By:JJTree&JavaCC: Do not edit this line. OrmWhereSqlParserConstants.java */
package org.smile.orm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OrmWhereSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int NOT_EQAUL = 2;
  /** RegularExpression Id. */
  int GREAT_EQAUL = 3;
  /** RegularExpression Id. */
  int LESS_EQAUL = 4;
  /** RegularExpression Id. */
  int LESS_THAN = 5;
  /** RegularExpression Id. */
  int GREAT_THAN = 6;
  /** RegularExpression Id. */
  int EQAUL = 7;
  /** RegularExpression Id. */
  int K_IS = 8;
  /** RegularExpression Id. */
  int LIKE = 9;
  /** RegularExpression Id. */
  int K_BOOLEAN = 10;
  /** RegularExpression Id. */
  int K_NULL = 11;
  /** RegularExpression Id. */
  int K_NOT = 12;
  /** RegularExpression Id. */
  int K_OR = 13;
  /** RegularExpression Id. */
  int K_AND = 14;
  /** RegularExpression Id. */
  int K_IN = 15;
  /** RegularExpression Id. */
  int S_LONG = 16;
  /** RegularExpression Id. */
  int S_INTEGERSTR = 17;
  /** RegularExpression Id. */
  int S_DOUBLESTR = 18;
  /** RegularExpression Id. */
  int S_FIELD = 19;
  /** RegularExpression Id. */
  int S_PARAMTER = 20;
  /** RegularExpression Id. */
  int S_FLAG_QUSTION = 21;
  /** RegularExpression Id. */
  int IN_MULTI_QUSTION = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int LETTER_DIGIT = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<NOT_EQAUL>",
    "<GREAT_EQAUL>",
    "<LESS_EQAUL>",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<K_IS>",
    "<LIKE>",
    "<K_BOOLEAN>",
    "\"null\"",
    "<K_NOT>",
    "<K_OR>",
    "<K_AND>",
    "<K_IN>",
    "<S_LONG>",
    "<S_INTEGERSTR>",
    "<S_DOUBLESTR>",
    "<S_FIELD>",
    "<S_PARAMTER>",
    "\"?\"",
    "<IN_MULTI_QUSTION>",
    "<LETTER>",
    "<LETTER_DIGIT>",
    "<DIGIT>",
    "<S_QUOTED_IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\",\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
  };

}
